import "%modules%/header/header";
import "%modules%/main/main";
import "%modules%/form/form";
import "%modules%/success/success";
import "%modules%/404/404";
import "%modules%/public-offer/public-offer";
import "%modules%/osago/osago";
import "%modules%/FAQ/FAQ";
import "%modules%/footer/footer";
